version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "task-master-app"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_prefix = "app"
disable_rollback = false
parameter_overrides = "CognitoDomain=\"capstone-task-master-ryan-horn\" S3Bucket=\"nss-s3-c04-capstone-task-master-ryan-horn\" FrontendDeployment=\"local\""
